CREATE SEQUENCE IF NOT EXISTS special_equipment_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE assignment
(
    request_id BIGINT NOT NULL,
    responder  BIGINT NOT NULL,
    CONSTRAINT pk_assignment PRIMARY KEY (request_id, responder)
);

CREATE TABLE medevac_request
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    location          VARCHAR(255),
    callsign          VARCHAR(255),
    patientnumber     INTEGER,
    precedence        INTEGER,
    litterpatient     INTEGER,
    ambulatorypatient INTEGER,
    security          CHAR,
    nationality       INTEGER,
    nbc               INTEGER,
    status            VARCHAR(255),
    CONSTRAINT pk_medevacrequest PRIMARY KEY (id)
);

CREATE TABLE medevac_request_marking_method
(
    medevac_request_id BIGINT NOT NULL,
    marking_method     VARCHAR(255)
);

CREATE TABLE medevac_request_special_equipment
(
    medevac_request_id   BIGINT NOT NULL,
    special_equipment_id BIGINT NOT NULL
);

CREATE TABLE nine_line_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    password VARCHAR(255),
    callsign VARCHAR(255),
    CONSTRAINT pk_ninelineuser PRIMARY KEY (id)
);

CREATE TABLE nine_line_user_roles
(
    nine_line_user_id BIGINT NOT NULL,
    roles_id          BIGINT NOT NULL
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE special_equipment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    special_equipment VARCHAR(255),
    CONSTRAINT pk_specialequipment PRIMARY KEY (id)
);

ALTER TABLE nine_line_user
    ADD CONSTRAINT uc_ninelineuser_username UNIQUE (username);

ALTER TABLE assignment
    ADD CONSTRAINT FK_ASSIGNMENT_ON_REQUEST FOREIGN KEY (request_id) REFERENCES medevac_request (id);
ALTER TABLE assignment
    ADD CONSTRAINT FK_ASSIGNMENT_ON_RESPONDER FOREIGN KEY (responder) REFERENCES nine_line_user (id);

ALTER TABLE medevac_request_marking_method
    ADD CONSTRAINT fk_medevacrequest_markingmethod_on_medevac_request FOREIGN KEY (medevac_request_id) REFERENCES medevac_request (id);

ALTER TABLE medevac_request_special_equipment
    ADD CONSTRAINT fk_medreqspeequ_on_medevac_request FOREIGN KEY (medevac_request_id) REFERENCES medevac_request (id);

ALTER TABLE medevac_request_special_equipment
    ADD CONSTRAINT fk_medreqspeequ_on_special_equipment FOREIGN KEY (special_equipment_id) REFERENCES special_equipment (id);

ALTER TABLE nine_line_user_roles
    ADD CONSTRAINT fk_ninlinuserol_on_nine_line_user FOREIGN KEY (nine_line_user_id) REFERENCES nine_line_user (id);

ALTER TABLE nine_line_user_roles
    ADD CONSTRAINT fk_ninlinuserol_on_role FOREIGN KEY (roles_id) REFERENCES role (id);