spring:
  main:
    web-application-type: servlet
  application:
    name: scrutinizer-api
  datasource:
    url: jdbc:postgresql://localhost:5450/scrutinizer
    username: scrutinizer
    password: scrutinizer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    operations-sorter: method
